# Generated by Django 2.0.5 on 2018-05-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='db_manage_contacts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('associated_user', models.CharField(max_length=254, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('last', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_local', models.CharField(max_length=20, null=True)),
                ('phone_mov', models.CharField(max_length=20, null=True)),
                ('street', models.CharField(max_length=150, null=True)),
                ('street_number', models.CharField(max_length=150, null=True)),
                ('population', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(max_length=150, null=True)),
                ('postalcode', models.CharField(max_length=12, null=True)),
                ('country', models.CharField(max_length=20, null=True)),
                ('url_web', models.URLField(max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='db_usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('last', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
