# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestor_usuarios', '0002_auto_20171006_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_manage_contacts',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
